//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReaderTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public Line()
        {
            this.Buses = new HashSet<Bus>();
            this.Paths = new HashSet<Path>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Bus> Buses { get; set; }
        public virtual ICollection<Path> Paths { get; set; }
    }
}
