//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReaderTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int BusId { get; set; }
        public string CurrentStation { get; set; }
        public string NextStation { get; set; }
        public System.TimeSpan ETA { get; set; }
        public System.TimeSpan CheckIn { get; set; }
    
        public virtual Bus Bus { get; set; }
    }
}
